matrix:
  include:
    - language: sh
      os: windows
      python: "3.6"
      env:
        - PIPENV_IGNORE_VIRTUALENVS=1
        - PIPENV_YES=1
      before_install: 
        - git config --global core.autocrlf true
      script:
        - choco install python --version 3.6
        - export JAVA_FOLDER=$(ls "C:/Program Files/Java")
        - export JAVA_HOME="C:/Program Files/Java/$JAVA_FOLDER"
        - echo $JAVA_HOME
        - ./gradlew.bat clean build -i --stacktrace